//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglamentTable
    {
        public int Id { get; set; }
        public string data { get; set; }
        public string info { get; set; }
    }
}
